answers/statistics-math.md
=> [펭귄] Fix typo

README.md
=> [펭귄] Fix toc link error

answers/deep-learning.md, answers/statistics-math-distribution.md
이미지 먼저 merge해서 preview에서 보이도록 수정했습니다. ☺️
=> [샐리] Update sally/deep-learning and statistics-math-distribution answer

answers/deep-learning.md
=> [히스] Add deep-learning

answers/statistics-math-distribution.md
=> [펭귄] Bernoui and binary distribution done

answers/deep-learning.md, answers/statistics-math-distribution.md
=> [원딜] deep-learning answer

README.md, answers/python.md
=> [펭귄] Add python interview questions

answers/python.md
=> [펭귄] Write all answers of python interview questions

answers/python.md
- self를 첫 번째 인자로 받지 않는 인스턴스 메서드를 호출할 경우 에러가 발생한다는 내용 추가
- 이상한 말 수정
- 볼드체 렌더링 안 되는 것 strong tag로 수정
- 참고 답변 지우지 않은 것 삭제
- "호출된 다음에 제너레이터가 생성한 요소가 어떻게 되는지?"에 대한 내용은 추가하지 않았습니다.
- 스터디 때 히스님이 말씀하신 대로 제너레이터지만 결국은 값을 반환한다는 점에서 보면 함수와 비슷합니다. 즉, 제너레이터가 생성한 요소를 저장하지 않으면 결국은 사라져버립니다.
- `==` 비교 연산자에 대한 내용 추가
- 오타 수정
- 순환 참조와 GC, 레퍼런스 카운트에 대한 내용 추가했습니다.
- 오타 수정
=> [펭귄] Fix typo and add more contents

answers/python.md
Reverts boostcamp-ai-tech-4/ai-tech-interview#86
=> Revert "[펭귄] Fix typo and add more contents"

answers/1-statistics-math.md
=> [펭귄] Resize latex rendering images

answers/4-python.md
=> [샐리] Update python feedback

answers/5-network.md
잘 모르는 내용이다보니까 글이 정리가 안되네요ㅠㅠㅠㅠ 블로그 글 거의 그대로 가져왔습니다,,,,
12번은,,,잘모르겠습니다,,,ㅠㅠㅠ
파이썬은 오늘 스터디 끝나고 최대한 빠르게 해서 올리겠습니다
=> [원딜] network answer

answers/4-python.md
좀 많이 늦었습니다 죄송합니다
도와주신 모든 분들 정말 감사합니다 죄송합니다
=> [원딜] python feedback

answers/8-algorithm.md
=> [원딜] Add algorithm answer

answers/8-algorithm.md
- 분할 정복과 다이나믹 프로그래밍은 코드가 간단해서 직접 작성했습니다.
- 위상 정렬이나 서로소 집합같은 경우 "이것이 취업을 위한 코딩테스트다" 코드를 참고해서 코드를 가져오지 않고 링크를 달아놨습니다.
=> [펭귄] Add algorithm answers

answers/7-data-structure.md
- 4-1 에서 서큘러 큐 동작방식 설명을 리스트 형식으로 변경하였습니다.
=> [히스] Update DS

answers/4-python.md
- `local var`, `global var` 위치 수정
=> [#139] 잘못된 설명 수정

answers/2-machine-learning.md
**1 문제 1 PR**
- 하나의 카테고리에서 한 개의 문제를 PR 해주세요.
**Merge 기준**
- 미적으로 나아졌을 경우
- 답변이 개선된 경우
**[카테고리] 번호**
아래 여덟가지 카테고리 중 하나를 선택하고 수정하려는 문제 번호를 적어주세요.
- Statistics/Math
- Machine Learning
- Deep Learning
- Python
- Network
- Operating System
- Data Structure
- Algorithm
`e.g. [Machine Learning] 12번`
해당 문제에서 **어디** 부분인지를 표시해주고, **어떻게** 수정했는지 **이유**와 함께 적어주세요.
=> Remove Test words

answers/1-statistics-math.md
- Statistics/Math 25번 문제의 출처 및 정답, 풀이를 추가하였습니다.
- images 내 폴더 네이밍 방법을 몰라서 일단 이미지를 클립보드로 복사해서 붙여넣었습니다.
=> Statistics/Math 25번 답변 추가

README.md, answers/2-machine-learning.md
- Global Minima \-\-\> Global Minimum 
Minima는 Minimum의 복수표현입니다.
Local minima는 복수개가 존재하므로 옳은 표현이지만, Global의 경우는 단 한개만 존재하기 때문에 Minima라는 표현은 적절하지 않습니다.
따라서 Global Minimum이 적절하다고 생각하여 수정하였습니다.
=> [Machine Learning] 3번

.mergify.yml
This change has been made by @CoodingPenguin from https://mergify.com config editor.
=> Mergify Configuration 파일 추가

answers/3-deep-learning.md
| **⚠ PR 템플릿 가이드는 삭제하지 말아주세요!** |
| --- |
> **`필수` 수정하려는 답변의 분야를 선택해주세요. 이외 수정사항은 기타를 선택하시고 오른쪽에 추가 설명 부탁드립니다.**
> **`필수` 어떻게 수정하셨는지 자세히 작성 부탁드립니다.**
15-3번 regularization
기존 설명이 부족하며 이해하기 위한 수식이 존재하지 않아 추가했습니다.
> **`선택` 수정 시 참고한 문서가 있다면 링크 작성 부탁드립니다.**
- [L1 and L2 regularization for Deep Learning - Ujwal Tewari's Medium](https://medium.com/analytics-vidhya/regularization-understanding-l1-and-l2-regularization-for-deep-learning-a7b9e4a409bf)
> **`필수` 아래 체크리스트 확인 부탁드립니다. 모두 체크된 PR만 확인 가능합니다.**
=> [딥러닝] 15-3번 regularization 설명 추가

answers/3-deep-learning.md
| **⚠ PR 템플릿 가이드는 삭제하지 말아주세요!** |
| --- |
> **`필수` 수정하려는 답변의 분야를 선택해주세요. 이외 수정사항은 기타를 선택하시고 오른쪽에 추가 설명 부탁드립니다.**
> **`필수` 어떻게 수정하셨는지 자세히 작성 부탁드립니다.**
`lacal` 오타를 `local`로 수정하였습니다.
> **`선택` 수정 시 참고한 문서가 있다면 링크 작성 부탁드립니다.**
> **`필수` 아래 체크리스트 확인 부탁드립니다. 모두 체크된 PR만 확인 가능합니다.**
=> [딥러닝] 14-2 답변 오타 수정

answers/2-machine-learning.md
| **⚠ PR 템플릿은 수정하지 말아주세요!** <br/> **🔥 [PR 작성 규칙](https://github.com/boostcamp-ai-tech-4/ai-tech-interview/discussions/182#discussion-4321560)을 준수하지 않는 PR은 거절됩니다. 꼭 읽어주세요.**|
| :--- |
> **`필수` 수정하려는 답변의 분야를 선택해주세요. 이외 수정사항은 기타를 선택하시고 오른쪽에 추가 설명 부탁드립니다.**
> **`필수` 어떻게 수정하셨는지 자세히 작성 부탁드립니다.**
머신러닝 8번 답변 중 Markov Chain 정의 부분의 pross -> process 로 오타 수정
> **`선택` 수정 시 참고한 문서가 있다면 링크 작성 부탁드립니다.**
> **`필수` 아래 체크리스트 확인 부탁드립니다. 모두 체크된 PR만 확인 가능합니다.**
=> [머신러닝] 8번 답변 오타 수정
